### ISSUE TITLE
remove a package 

### ISSUE THREAD

**Issue by ctf0** [liajoy/vscode-goto-package#3]
is it possible to also add an option to remove the package ?

**Comment by liajoy** [comment]
remove a package dependence from `package.json` and remove all the files from `nodel_modules` ?

**Comment by ctf0** [comment]
yes, simply run `npm remove package_name` and the command will take of everything else

**Comment by liajoy** [comment]
Just run `npm remove package_name` is convenient. (for me
And `npm remove package_name` is not so fast sometimes, a loading animation is required. After package has been removed, user will be notified. Seems is
Anyway it's a nice feature, but i don't have time to do this for now. If you really want this feature, you can do it by yourself.

**Comment by ctf0** [comment]
can u at least tell me where should i start ?

**Comment by liajoy** [comment]
You can get package's path and name [here](https://github.com/liajoy/vscode-goto-package/blob/master/src/commands.ts#L68).
when package picked, do anything you want [here](https://github.com/liajoy/vscode-goto-package/blob/master/src/commands.ts#L102). (maybe use `child_process ` to rum remove command
